version: '2'
services:
  flink-master:
    image: ging/flink-master:1.6.1-hadoop2.8 
    hostname: flink-master
    container_name: flink-master
    environment:
      - FLUENT_HOST=fluent
      - FLUENT_PORT=24224
      - INIT_DAEMON_STEP=setup_flink
    ports:
      - "8080:8080"
      - "8081:8081"

  flink-worker:
    image: ging/flink-worker:1.6.1-hadoop2.8
    hostname: flink-worker
    container_name: flink-worker
    environment:
      - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
      - FLUENT_HOST=fluent
      - FLUENT_PORT=24224
    ports:
      - "9001:9001"
    depends_on:
      - "flink-master"
  
  fluent:
    image: fluent/fluent-bit
    hostname: fluent
    container_name: fluent
    volumes:
      - ./fluent/flink_to_cep.conf:/fluent-bit/etc/flink_to_cep.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    command:
      -/fluent-bit/bin/fluent-bit -c /fluent-bit/etc/flink_to_cep.conf     
  
  mongo:
    image: mongo:3.4
    command: --nojournal
  orion:
    image: fiware/orion
    links:
      - mongo
    ports:
      - "1026:1026"
    command: -dbhost mongo
