version: '2'
services:
  flink-master:
    image: ging/flink-master:1.6.1-hadoop2.8 
    hostname: flink-master
    container_name: flink-master
    environment:
      - FLUENT_HOST=fluent
      - FLUENT_PORT=24224
      - INIT_DAEMON_STEP=setup_flink
    ports:
      - "8080:8080"
      - "8081:8081"

  flink-worker:
    image: ging/flink-worker:1.6.1-hadoop2.8
    hostname: flink-worker
    container_name: flink-worker
    environment:
      - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master
      - FLUENT_HOST=fluent
      - FLUENT_PORT=24224
    depends_on:
      - "flink-master"
  fluent:
    image: ging/fluent
    hostname: fluent
    container_name: fluent
    volumes:
      - /opt/data:/fluentd/log
      - /opt/data:/fluentd/etc
    environment:
      - FLUENTD_CONF=yours.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - "kafka_1"      
  kafka_1:
    image: ging/kafka:0.11.0.2
    hostname: kafka_1
    container_name: kafka_1
    environment:
      - ADVERTISED_HOST=kafka_1
      - ADVERTISED_PORT=9092
    ports:
      - "2181:2181"
      - "9092:9092"
