apiVersion: v1
kind: Pod
metadata:
  name: config-orion
  namespace: usage-control
spec:
  restartPolicy: Never
  containers:
  - name: config-orion
    image: curlimages/curl
    command: ["curl", "http://orion:1026/v2/entities","-s","-S", "-H","Content-Type: application/json","-d",'{"id": "ticket","type": "ticket","_id": {"type": "String","value": 14},"mall": {"type": "String","value": 1},"date": {"type": "date","value": "01/14/2016"},"client": {"type": "int","value": 77014474650},"items": {"type": "object","value": {}}}']
    ports:
    - containerPort: 80

