apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-mongo
  namespace: usage-control
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: local-storage
  resources:
    requests:
      storage: 50Gi
