apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: fiware-idm
  name: fiware-idm
  namespace: usage-control
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fiware-idm
    spec:
      containers:
      - env:
        - name: IDM_DB_HOST
          value: mysql
        - name: IDM_PTP_HOST
          value: ptp
        - name: IDM_PTP_PORT
          value: "8092"
        - name: IDM_USAGE_CONTROL_ENABLED
          value: "true"
        - name: IDM_DB_PASS
          value: "idm"
        - name: IDM_DB_USER
          value: "root"
        - name: DEBUG
          value: "idm:*"
        image: fiware/idm
        name: fiware-idm
        ports:
        - containerPort: 3000
        - containerPort: 443
        stdin: true
        tty: true
      restartPolicy: Always
