apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: usage-control
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - args:
        - --nojournal
        image: mongo:3.4
        name: mongo
      restartPolicy: Always

