apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: usage-control
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env: 
        - name: MYSQL_ROOT_PASSWORD
          value: idm
        image: mysql:5.7  
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
#        volumeMounts:
#        - mountPath: /var/lib/mysql
#          subPath: mysql
#          name: vol-mysql
      restartPolicy: Always
#      volumes:
#      - name: vol-mysql
#        persistentVolumeClaim:
#          claimName: vol-mysql
