apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pep-ptp
  name: pep-ptp
  namespace: usage-control
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pep-ptp
    spec:
      containers:
      - env:
        - name: PEP_PASSWORD
          value: pep_proxy_9112a0a7-1244-4e4d-95bf-ee472de422ed
        - name: PEP_PROXY_APP_HOST
          value: flink-taskmanager
        - name: PEP_PROXY_APP_ID
          value: 18d0cd90-8684-4e84-b806-c34f5d18ff02
        - name: PEP_PROXY_APP_PORT
          value: "9200"
        - name: PEP_PROXY_IDM_HOST
          value: fiware-idm
        - name: PEP_PROXY_IDM_PORT
          value: "3000"
        - name: PEP_PROXY_PORT
          value: "24225"
        - name: PEP_PROXY_USERNAME
          value: pep_proxy_349d12d4-eb57-41d7-8bd4-1e5a7015f4eb
        image: ging/pep-ptp
        name: pep-ptp
        ports:
        - containerPort: 24225
      restartPolicy: Always
