apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: usage-control
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - env:
        - name: FLINK_MASTER_PORT_6123_TCP_ADDR
          value: flink-jobmanager
        name: taskmanager
        image: ging/flink-cep-worker:1.7.2-hadoop2.8
#        workingDir: /opt/flink
#        command: ["/bin/bash", "-c", "$FLINK_HOME/bin/taskmanager.sh start; \
#          while :;
#          do
#            if [[ -f $(find log -name '*taskmanager*.log' -print -quit) ]];
#              then tail -f -n +1 log/*taskmanager*.log;
#            fi;
#          done"]
        ports:
        - containerPort: 6122
          name: rpc
          containerPort: 9200
          name: traces
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 60
#        volumeMounts:
#        - name: flink-config-volume
#          mountPath: /opt/flink/conf/
#      volumes:
#      - name: flink-config-volume
#        configMap:
#          name: flink-config
#          items:
#          - key: flink-conf.yaml
#            path: flink-conf.yaml
#          - key: log4j.properties
#            path: log4j.properties
