apiVersion: v1
kind: Service
metadata:
  labels:
    app: dataset
  name: dataset
  namespace: usage-control
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: dataset
status:
  loadBalancer: {}
