apiVersion: v1
kind: Service
metadata:
  labels:
    app: fiware-idm
  name: fiware-idm
  namespace: usage-control
spec:
  type: LoadBalancer
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    app: fiware-idm
