apiVersion: v1
kind: Service
metadata:
  name: jobmanager-rest
  namespace: usage-control
spec:
  type: LoadBalancer
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
  selector:
    app: flink
    component: jobmanager
