apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-ds
  name: mongo-ds
  namespace: usage-control
spec:
  ports:
  - name: "mongo-ds"
    port: 27017
  selector:
    app: mongo-ds
  clusterIP: None

