apiVersion: v1
kind: Service
metadata:
  labels:
    app: orion
  name: orion
  namespace: usage-control
spec:
  ports:
  - name: "orion"
    port: 1026
    targetPort: 1026
  selector:
    app: orion
  type: LoadBalancer

