apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager
  namespace: usage-control
spec:
  clusterIP: None
  ports:
  - name: logs
    port: 9200
  selector:
    app: flink
    component: taskmanager
