nginx:
  build: ./nginx
  hostname: nginx
#    networks:
 #     - flink
#  container_name: nginx
  ports:
    - "8080:80"
flinkmaster:
    image: bde2020/flink-master:latest
    hostname: flink-master
    environment:
      - INIT_DAEMON_STEP=setup_flink
#    networks:
#      - flink
flinkworker:
    image: bde2020/flink-worker:latest
    hostname: flink-worker
#    networks:
#     - flink
    links:
      - "flinkmaster:flink-master"

#networks:
# flink:
